# Generated by Django 4.2 on 2026-06-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_customuser_options_customuser_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('transporter', 'Transporter'), ('logistics', 'Logistics')], default='customer', max_length=20),
        ),
    ]
