# Generated by Django 4.2 on 2026-06-18 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_alter_customuser_options_customuser_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransporterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_registration_number', models.CharField(max_length=50, unique=True)),
                ('license_number', models.CharField(max_length=50)),
                ('business_license', models.FileField(upload_to='licenses/')),
                ('office_address', models.TextField()),
                ('office_phone', models.CharField(max_length=15)),
                ('office_email', models.EmailField(max_length=254)),
                ('year_established', models.IntegerField()),
                ('number_of_vehicles', models.IntegerField()),
                ('coverage_area', models.TextField(help_text='Coverage cities/states')),
                ('registration_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=5.0, help_text='1-5 rating')),
                ('total_deliveries', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transporter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transporter Profile',
                'verbose_name_plural': 'Transporter Profiles',
                'db_table': 'transporter_profile',
            },
        ),
        migrations.CreateModel(
            name='TransporterVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('capacity', models.DecimalField(decimal_places=2, help_text='Capacity in kg', max_digits=10)),
                ('registration_number', models.CharField(max_length=50)),
                ('insurance_number', models.CharField(max_length=50)),
                ('pollution_certificate', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Under Maintenance'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='transporterapp.transporterprofile')),
            ],
            options={
                'verbose_name': 'Transporter Vehicle',
                'verbose_name_plural': 'Transporter Vehicles',
                'db_table': 'transporter_vehicle',
            },
        ),
        migrations.CreateModel(
            name='ShipmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='assigned', max_length=20)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('assignment_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='userapp.shipment')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transporterapp.transporterprofile')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transporterapp.transportervehicle')),
            ],
            options={
                'verbose_name': 'Shipment Assignment',
                'verbose_name_plural': 'Shipment Assignments',
                'db_table': 'transporter_assignment',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, default=0, help_text='Platform commission', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_date', models.DateField()),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='transporterapp.shipmentassignment')),
                ('transporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='transporterapp.transporterprofile')),
            ],
            options={
                'verbose_name': 'Earnings',
                'verbose_name_plural': 'Earnings',
                'db_table': 'transporter_earnings',
                'ordering': ['-earned_date'],
            },
        ),
    ]
